schedules:
- cron: "15 22 * * *"
  displayName: Master nightly build
  branches:
    include:
    - master
  always: true
jobs:
- job: Linux
  pool:
    vmImage: ubuntu-20.04
  strategy:
    matrix:
      ArchLinux:
        os: 'archlinux/base'
  steps:
  - script: docker run
              --volume $PWD:/host
              --workdir /host/continuous-integration
              --env "PYTHONDONTWRITEBYTECODE=1"
              $(os)
              bash -c "./setup.sh &&
                       ./lint.sh &&
                       ./test.sh"
    displayName: 'Build, lint and test on Archlinux'
- job: BuildDeploymentImage
  pool:
    vmImage: ubuntu-20.04
  steps:
  - script: docker build -t arch-deployment -f deployment/Dockerfile .
    displayName: 'Test building of deployment image '